#!/bin/sh

echo "Let's see your code first..."

# Check if there's any .go files staged first
# If there is not, then proceed without checks
files=$(git diff --cached --name-only --diff-filter=ACM | grep ".go$")
if [ "$files" = "" ]; then
    exit 0
fi

# Run linter, store output
lint_output=$(make lint)

# Include test command here

if [ -z "${lint_output}" ]; then
    echo "\033[32mEverything's fine, go ahead!\033[0m"
else
    echo "\033[31mHey, hold on! Check the errors first!\033[0m"
    echo "${lint_output}"
    exit 1
fi
